---
name: lint

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r package-requirements.txt
        pip install -r requirements.txt
    - name: Lint
      run: |
        pyroma .
        pylint im_jenkins_server.py
        python setup.py bdist_wheel
