---
name: publish

# Actions for any PyPI-like tag (i.e. 'pypi*.)

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# PYPI_USERNAME
# PYPI_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
    tags:
    - pypi*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r package-requirements.txt
        pip install -r requirements.txt
    - name: Build
      run: python setup.py bdist_wheel
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_TOKEN }}
